config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :savings
  get 'dashboard/dashboard'
  
  resources :navigations
  resources :finance_states
  resources :accounts
  resources :monthly_statistics
  resources :items
  resources :intervals
  resources :categories
  resources :savings
  
  root to: 'dashboard#dashboard'
  
  get '/calculate_amount', to: 'items#calculate_amount'
  get '/get_pie_data', to: 'monthly_statistics#get_pie_data'
  get '/get_salaries', to: 'monthly_statistics#get_salaries'
  get '/get_date_of_last_income', to: 'monthly_statistics#get_date_of_last_income'
  get '/get_date_of_first_income', to: 'monthly_statistics#get_date_of_first_income'
   
  #get '/delete_all', to: 'monthly_statistics#delete_all'
  get '/get_item', to: 'items#get_item'
  get '/get_expenses_grouped', to: 'dashboard#get_expenses_grouped'
  
  resources :items do
    collection { post :import }  
  end
  
  resources :categories do
    collection { post :import }
  end
  
  resources :intervals do
    collection { post :import }
  end
  
  resources :navigations do
    collection { post :import }
  end
  
  resources :accounts do
    collection { post :import }
  end
  
  resources :finance_states do
    collection { post :import }
    collection { post :synchronize }
    collection { post :delete_all }
  end
  
  resources :monthly_statistics do
    collection { post :import }
    collection { post :delete_all }
  end
    
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/finance_state.rb
class FinanceState < ApplicationRecord
  belongs_to :account
  
  def self.synchronize(current_user)
    
    @counter = 0
    #HibiscusTransaction.all.order(valuta: :desc).each_with_index do |transaction, index|
    Account.where(:user_id => current_user.id).order(hibiscus_account_id: :asc).each do |account|
      @current_account = account.hibiscus_account_id
      logger.debug "CURRENT ACCOUNT: " + @current_account.to_s
      #"New article: #{@article.attributes.inspect}"
      #puts "CURRENT ACCOUNT: " + @current_account.to_s
      
      if FinanceState.where(:account_id => account.id).last.present? 
          @id_last_synchronization = FinanceState.where(:account_id => account.id).last.hibiscus_sync_id + 1
      else
          @id_last_synchronization = "1"
      end
      
      @id_last_synchronization_hibiscus = HibiscusTransaction.where(:konto_id => @current_account).order(id: :asc).last.id
      
      logger.debug "LAST SYNCHRONIZATION ID (FINANCE STATE): " + @id_last_synchronization.to_s
      logger.debug "HIBISCUS TRANSACTION ID: " + @id_last_synchronization_hibiscus.to_s
      
      if @id_last_synchronization != @id_last_synchronization_hibiscus
      
        HibiscusTransaction.where(:konto_id => @current_account).order(id: :asc).find_each(start: @id_last_synchronization) do |transaction|
          @counter += 1
          
          logger.debug "CURRENT HIBISCUS ID: " + transaction.id.to_s
          
          @hibiscus_sync_id = transaction.id
          @period = transaction.valuta.to_date
          @actual_value = transaction.betrag.to_f
          @item_id = 34
          @planned_value = Item.find(@item_id).amount_calculated
          @match_confidence = nil
          @match_type = nil
          @match_value = nil
          @internal_transaction = false
          @reserve_release = false
          @reserve_payment = false
          @text = transaction.zweck.to_s + transaction.zweck2.to_s + transaction.zweck3.to_s
          
          if transaction.empfaenger_name.present?
            if transaction.empfaenger_name.upcase == 'TIMO HILBRING'
              logger.debug "INTERNAL TRANSACTION identified by user name"
              @internal_transaction = true
            end
          else
            if transaction.empfaenger_konto.present?
              if Account.where('iban = ?', transaction.empfaenger_konto).first.present?
                logger.debug "INTERNAL TRANSACTION identified by internal account: " + account.iban.to_s + ' -> ' + transaction.empfaenger_konto.to_s
                @internal_transaction = true
              else
                if Account.where('account_number = ?', transaction.empfaenger_konto).first.present?
                  logger.debug "INTERNAL TRANSACTION identified by internal account: " + account.account_number.to_s + ' -> ' + transaction.empfaenger_konto.to_s
                  @internal_transaction = true
                end              
              end
            end
          end
          
          #Item.all.each do |item|
          Item.where(:active => true, :user_id => current_user.id).find_each do |item|
            #puts "CURRENT ITEM: " + item.id.to_s          
            @match = match_item_to_transaction(account, item, transaction)
        
            if @match.present?
              @match_confidence = @match["confidence"].to_f 
              @match_type = @match["match_type"]
              @match_value = @match["match_value"]
              
              if @match_value.present?
                #@match["match_type"] != "default"
                #logger.debug "USING DEFAULT VALUE"
                @planned_value = item.amount_calculated
                @item_id = item.id
                
                if @actual_value < 0   #debit => outgoing transaction
                  if @item_id != 34   #item found => not unclassified
                    matched_item = Item.find(@item_id)
                    if matched_item.reserve == true
                      external_account = find_by_account(matched_item.external_account.split("|"), transaction)
                      if external_account.present? #and transaction.art == 'Kontouebertrag'
                         #@match_type.to_s.include? "external_account" or @match_type.to_s.include? "item_name"
                        if @internal_transaction == true
                          @reserve_release = true
                          logger.debug  "Reserve " + matched_item.name + " released on " + @period.to_s
                        else
                          @reserve_release = true
                          @reserve_payment = true
                          logger.debug  "Reserve " + matched_item.name + " released & payed on " + @period.to_s
                        end
                        matched_item.update(:maturity => transaction.valuta)
                      end
                    end
                  end
                end
                
                break   
              end
                    
            end                      
          end   #end item
          
          if not @match_value.present?
            if account.item_id.present?
              @planned_value = Item.find(account.item_id).amount_calculated
              @item_id = account.item_id
              @match_type = "default"
              @match_value = @item_id
              @match_confidence = 0.0
            end
          end
          logger.debug  "CREATE MONTHLY STATISTIC"
          statistic = MonthlyStatistic.create(:period => @period, :planned_value => @planned_value, :actual_value => @actual_value, :item_id => @item_id, :hibiscus_sync_id => @hibiscus_sync_id, :match_confidence => @match_confidence, :match_type => @match_type, :match_value => @match_value, :account_id => account.id, :internal_transaction => @internal_transaction, :reserve_release => @reserve_release, :reserve_payment => @reserve_payment, :text => @text)
          @last_synchronized = transaction.valuta
          @balance = transaction.saldo
          @hibiscus_id = transaction.id
          @payment = true
          
          Transaction.create(:account_id => account.id, :monthly_statistic_id => statistic.id)
          
        end   #end hibsicus_transaction
        
        if @last_synchronized.present?
          @current_finance_state= FinanceState.where(:account_id => account.id).order(period: :asc).last
          if @current_finance_state.present?
            logger.debug "USE EXISTING FINANCE STATE: " + @current_finance_state.id.to_s
            @current_finance_state.update(:period => @last_synchronized, :hibiscus_sync_id => @hibiscus_id, :balance => @balance)
            #@current_finance_state.period = @last_synchronized
            #@current_finance_state.hibiscus_sync_id = @hibiscus_id
            #@current_finance_state.balance = @balance
          else
            logger.debug "CREATE FINANCE STATE"      
            FinanceState.create(:period => @last_synchronized, :hibiscus_sync_id => @hibiscus_id, :balance => @balance, :account_id => account.id)
          end
          @last_synchronized = nil
          @balance = nil
          @hibiscus_id = nil
        end
      
      else
        logger.debug "Finance state up to date. No synchronization performed."
      end
    end #end account
    logger.debug "Total transaction: " + @counter.to_s
    #HibiscusTransaction.all.order(valuta: :desc).each_with_index do |transaction, index|
  end
  
  def self.assign_result(hash, match_type, match_confidence, match_value)
    
    delimiter = '|'
    
    if hash["match_type"].present? 
        hash["match_type"] = hash["match_type"] + delimiter + match_type.to_s
    else
        hash["match_type"] = match_type.to_s
    end
    if hash["match_value"].present? 
        hash["match_value"] = hash["match_value"] + delimiter + match_value.to_s
    else
        hash["match_value"] = match_value.to_s
    end
    if hash["confidence"].present? 
        hash["confidence"] = hash["confidence"].to_f + match_confidence.to_f
    else
        hash["confidence"] = match_confidence.to_f
    end
       
  end
  
  def self.match_item_to_transaction(account, item, transaction)
    
    @return = Hash.new
    @return["match_type"] = nil
    @return["match_value"] = nil
    @return["confidence"] = 0

    # try to match via external account
    if item.external_account.present?
      @account_found = find_by_account(item.external_account.split("|"), transaction)
      if @account_found.present?
        #if item.reserve.present?
          if item.reserve == false
            #@return["match_type"] = "external_account"
            assign_result(@return, "external_account", 0.5, @account_found)
            logger.debug "TRANSACTION FOUND BY EXTERNAL ACCOUNT " + @account_found
          end
        #end
        #return @return
      end
    end
    
    # try to match via key words
    if item.key_words.present?
      @keyword_found = find_by_keyword(item.key_words.split("|"), transaction)
      if @keyword_found.present?
        assign_result(@return, "key_word", 0.5, @keyword_found)
        logger.debug "TRANSACTION FOUND BY KEY WORD " + @keyword_found.to_s
        #return @return        
      end
    end
    
    # try to match via item name
    if item.name.present?
      @keyword_found = find_by_name(item.name, transaction)
      if @keyword_found.present?
        assign_result(@return, "item_name", 0.5, @keyword_found)
        logger.debug "TRANSACTION FOUND BY NAME " + @keyword_found.to_s
        #return @return        
      end
    end
    
    # match via (internal/default) account
    #if item.account_id.present?
    #  if account.id == item.account_id
    #    #if transaction.empfaenger_konto == Account.find(item.account_id).iban
    #    @confidence = @return["confidence"].to_f
    #    if @confidence == 0 && item.reserve == false
    #      assign_result(@return, "default", 0.5, item.account_id )

app/controllers/finance_states_controller.rb
class FinanceStatesController < ApplicationController
  before_action :set_finance_state, only: [:show, :edit, :update, :destroy]
  respond_to :html, :json
  add_flash_types :success, :warning, :danger, :info

  # GET /finance_states
  # GET /finance_states.json
  def index
    respond_to do |format|
    format.html
    format.json { render json: FinanceStatesDatatable.new(view_context) }
    end
  end

  # GET /finance_states/1
  # GET /finance_states/1.json
  def show
    @finance_state = FinanceState.find(params[:id])
  end

  # GET /finance_states/new
  def new
    @finance_state = FinanceState.new
  end

  # GET /finance_states/1/edit
  def edit
    @finance_state = FinanceState.find(params[:id])
  end

  # POST /finance_states
  # POST /finance_states.json
  def create
    @finance_state = FinanceState.new(finance_state_params)

    respond_to do |format|
      if @finance_state.save
        format.html { redirect_to @finance_state, notice: 'Finance state was successfully created.' }
        format.json { render :show, status: :created, location: @finance_state }
      else
        format.html { render :new }
        format.json { render json: @finance_state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /finance_states/1
  # PATCH/PUT /finance_states/1.json
  def update
    respond_to do |format|
      if @finance_state.update(finance_state_params)
        format.html { redirect_to @finance_state, notice: 'Finance state was successfully updated.' }
        format.json { render :show, status: :ok, location: @finance_state }
      else
        format.html { render :edit }
        format.json { render json: @finance_state.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /finance_states/1
  # DELETE /finance_states/1.json
  def destroy
    @finance_state.destroy
    respond_to do |format|
      format.html { redirect_to finance_states_url, notice: 'Finance state was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def synchronize
    FinanceState.synchronize(current_user)
    redirect_to finance_states_path, success: "Statistics created"
  end
  
  def import
    FinanceState.import(params[:file])
    redirect_to finance_states_path, notice: "Finance state data imported"
  end
  
  def delete_all
    FinanceState.delete_all
    redirect_to finance_states_path, notice: "All finance states deleted"    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_finance_state
      @finance_state = FinanceState.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def finance_state_params
      params.require(:finance_state).permit(:period, :hibiscus_sync_id, :balance, :account_id)
    end
end

app/helpers/finance_states_helper.rb
module FinanceStatesHelper
end

app/views/finance_states/_form.html.erb
<%= form_with(model: finance_state, local: true) do |form| %>
  <% if finance_state.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(finance_state.errors.count, "error") %> prohibited this finance_state from being saved:</h2>

      <ul>
      <% finance_state.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :period %>
    <%= form.date_select :period, id: :finance_state_period %>
  </div>

  <div class="field">
    <%= form.label :hibiscus_sync_id %>
    <%= form.number_field :hibiscus_sync_id, id: :finance_state_hibiscus_sync_id %>
  </div>

  <div class="field">
    <%= form.label :balance %>
    <%= form.text_field :balance, id: :finance_state_balance %>
  </div>

  <div class="field">
    <%= form.label :account_id %>
    <%= form.text_field :account_id, id: :finance_state_account_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/finance_states/edit.html.erb
<h1>Editing Finance State</h1>

<%= render 'form', finance_state: @finance_state %>

<%= link_to 'Show', @finance_state %> |
<%= link_to 'Back', finance_states_path %>

app/views/finance_states/index.html.erb
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
	<!-- Content Header (Page header) -->
	<section class="content-header">
		<h1> Monthly planning <small>Income vs. expenses</small></h1>
	  	<%= render 'navigations/navigation_bar' %>
	  	<%= render 'layouts/state_info' %>
	</section>

	<!-- Main content -->
	<section class="content">
		<%= render 'finance_states/diagram' %>
		<div class="row">
			<div class="col-xs-12">
				<div class="box">
					<div class="box-header">
						<h3 class="box-title">Data Table With Full Features</h3>
					</div>
					<!-- /.box-header -->
					<div class="box-body">
						<table style="width: 67%; margin: 0 auto 2em auto;" cellspacing="0" cellpadding="3" border="0">
							<thead>
								<tr>
									<th>Filter</th>
								</tr>
							</thead>
							<tbody>

							</tbody>
						</table>
						<table id="example1" class="display" data-source="<%= finance_states_url(format: "json") %>">
						  <thead>
						    <tr>
						      <th>Period</th>
						      <th>Hibiscus sync</th>
						      <th>Balance</th>
						      <th>Account</th>
						      <th>Edit</th>
						      <th>Delete</th>
						    </tr>
						  </thead>
							<tbody>
								<!-- automatically filled by items controller -->
							</tbody>
						</table>
					</div>
					<!-- /.box-body -->
				</div>
				<!-- /.box -->
			</div>
			<!-- /.col -->
		</div>
		<!-- /.row -->
		<div>
			<h4>Create statistics</h4>
			<%= form_tag synchronize_finance_states_path, multipart: true do %>
			<%= submit_tag "Create statistics" %>
			<% end %>
		</div>
		<div>
			<h4>Import Statistics</h4>
			<%= form_tag import_finance_states_path, multipart: true do %>
			<%= file_field_tag :file %>
			<%= submit_tag "Import CSV" %>
			<% end %>
			<%= link_to 'New Account', new_finance_state_path %>
		</div>
		<div class="form-group">
          <label for="financeStatesDeleteAll">Delete all</label>
          	<%= form_tag delete_all_finance_states_path, multipart: true do %>
			<button type="submit" class="btn btn-primary">Delete all</button>
			<% end %>
        </div>
	</section>
	<!-- /.content -->
</div>
<!-- /.content-wrapper -->
<script type="text/javascript">
	var tableId = '#example1'
	myFunction(tableId)
</script>

app/views/finance_states/new.html.erb
<h1>New Finance State</h1>

<%= render 'form', finance_state: @finance_state %>

<%= link_to 'Back', finance_states_path %>

app/views/finance_states/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Period:</strong>
  <%= @finance_state.period %>
</p>

<p>
  <strong>Hibiscus sync:</strong>
  <%= @finance_state.hibiscus_sync_id %>
</p>

<p>
  <strong>Balance:</strong>
  <%= @finance_state.balance %>
</p>

<p>
  <strong>Account:</strong>
  <%= @finance_state.account %>
</p>

<%= link_to 'Edit', edit_finance_state_path(@finance_state) %> |
<%= link_to 'Back', finance_states_path %>