config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :savings
  get 'dashboard/dashboard'
  
  resources :navigations
  resources :finance_states
  resources :accounts
  resources :monthly_statistics
  resources :items
  resources :intervals
  resources :categories
  resources :savings
  
  root to: 'dashboard#dashboard'
  
  get '/calculate_amount', to: 'items#calculate_amount'
  get '/get_pie_data', to: 'monthly_statistics#get_pie_data'
  get '/get_salaries', to: 'monthly_statistics#get_salaries'
  get '/get_date_of_last_income', to: 'monthly_statistics#get_date_of_last_income'
  get '/get_date_of_first_income', to: 'monthly_statistics#get_date_of_first_income'
   
  #get '/delete_all', to: 'monthly_statistics#delete_all'
  get '/get_item', to: 'items#get_item'
  get '/get_expenses_grouped', to: 'dashboard#get_expenses_grouped'
  
  resources :items do
    collection { post :import }  
  end
  
  resources :categories do
    collection { post :import }
  end
  
  resources :intervals do
    collection { post :import }
  end
  
  resources :navigations do
    collection { post :import }
  end
  
  resources :accounts do
    collection { post :import }
  end
  
  resources :finance_states do
    collection { post :import }
    collection { post :synchronize }
    collection { post :delete_all }
  end
  
  resources :monthly_statistics do
    collection { post :import }
    collection { post :delete_all }
  end
    
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/monthly_statistic.rb
class MonthlyStatistic < ApplicationRecord
  belongs_to :item, optional: true
  has_many :transactions, :class_name => 'Transaction'
  has_many :accounts, :through => :transactions
  
  def get_pie_data
    data = Array.new   
    if start_date.present?
      @chart = MonthlyStatistic.where('period BETWEEN ? AND ?', start_date, end_date).joins(:item)
      @expenses_pie = @chart.where('actual_value < 0').group(:name).sum(:actual_value)                    
      @expenses_pie.find_all do |item|
        actual_value = item[1].to_f*-1
        row = [item[0], actual_value]
        data.push(row)
      end
    end
    get_pie_data = data
  end
  
  def self.get_salaries(user_id)
    @statistics = MonthlyStatistic.all.order(period: :asc)
    #@month_dates = nil
    @month_dates = Hash.new
    if Item.where(:name => 'Nettogehalt', :user_id => user_id).first.present?
      key_words = Item.where(:name => 'Nettogehalt', :user_id => user_id).first.key_words.split("|")
    
      key_words.each_with_index do |key_word, index|
        @salaries = @statistics.where('match_value LIKE ?', '%' + key_word + '%') 
        @salaries.find_each.with_index do |statistic, index|
          @month_date = Hash.new
          month_name = statistic.period.beginning_of_month.next_month.strftime("%B %Y").to_s
          transaction_id = statistic.id
          start_date = MonthlyStatistic.find(transaction_id).period
          if index +1 < @salaries.size
            puts @salaries[index+1].period.to_s
            end_date = @salaries[index+1].period-1 #Date.current.end_of_month
          else
            end_date = Date.current.end_of_month
          end
          @month_date = {"index" => index, "month" => month_name, "start_date" => start_date, "end_date" => end_date, "id" => transaction_id}
          @month_dates[transaction_id.to_s] = @month_date
        end
      end
    end
    #puts @month_dates
    return @month_dates
  end
 
  def self.get_date_of_last_income(user_id)
    salaries = get_salaries(user_id)
    if salaries.values[salaries.size-1].present?
      result = salaries.values[salaries.size-1]
    end
    return result    
  end
  
  def self.get_date_of_first_income(user_id)
    salaries = get_salaries(user_id)
    result = Date.current.beginning_of_month
    if salaries.values[0].present?
      result = salaries.values[0]
    end
    return result    
  end
  
  def self.get_expenses_for_month(id, user_id)
    date_range_month = get_start_end_date_for_month(id, user_id)
    return get_expenses(date_range_month["start_date"], date_range_month["end_date"], user_id)
  end
  
  def self.get_income_for_month(id, user_id)
    date_range_month = get_start_end_date_for_month(id, user_id)
    return get_income(date_range_month["start_date"], date_range_month["end_date"], user_id)
  end
  
  def self.get_balance_for_month(id, user_id)
    return get_income_for_month(id, user_id) + get_expenses_for_month(id, user_id)
  end
  
  def self.get_start_end_date_for_month(id, user_id)
    result = Hash.new
    salary = MonthlyStatistic.get_salaries(user_id)[id]
    result["start_date"] = salary["start_date"].to_s
    result["end_date"]  = salary["end_date"].to_s
    return result
  end
  #@transactions.where('actual_value < 0 and budget = false and internal_transaction =false').sum(:actual_value) 
  def self.get_expenses(start_date, end_date, user_id)
    expenses = collect_monthly_expenses_clean(start_date, end_date, user_id).sum(:actual_value)
    #transactions.where('actual_value < 0 and (internal_transaction = false or savings = true) and reserve = false ').or(transactions.where('actual_value < 0 and reserve = true and reserve_release = false and reserve_payment = false')).sum(:actual_value)
    #reserves = transactions.where('actual_value < 0 and reserve = true and reserve_release = false').sum(:actual_value)
    return expenses #+ reserves
  end
  
  #@transactions.where('actual_value > 0 And reserve = false and budget = false and savings = false and internal_transaction =false'
  def self.get_income(start_date, end_date, user_id)
    return get_statistics_between(start_date, end_date, user_id).where('actual_value > 0 And reserve = false and (budget = false or savings_id <> 4) and internal_transaction =false').sum(:actual_value)
  end
  
  def self.get_balance(start_date, end_date, user_id)
    return get_income(start_date, end_date, user_id) + get_expenses(start_date, end_date, user_id)
  end
  
  def self.get_statistics_between(start_date, end_date, user_id)
    return MonthlyStatistic.where('period BETWEEN ? AND ? AND user_id = ?', start_date, end_date, user_id).joins(:item)
  end
  
  def self.get_expenses_grouped(start_date, end_date, user_id, group_by)
    #transactions = get_statistics_between(start_date, end_date)
    #expenses = transactions.where('actual_value < 0 and (internal_transaction = false or savings = true) and reserve = false').or(transactions.where('actual_value < 0 and reserve = true and (reserve_release = false and reserve_payment = false)'))
    #reserves = transactions.where('actual_value < 0 and reserve = true')
    #grouped_expenses = expenses
    #MonthlyStatistic.where('actual_value < 0 and monthly_statistics.id In (Select * from monthly_statistics where internal_transaction = false and period BETWEEN ? AND ?) UNION (Select * from monthly_statistics where reserve = false and period BETWEEN ? AND ?)', start_date, end_date, start_date, end_date).joins(:item) #expenses.merge(reserves)
    return collect_monthly_expenses_clean(start_date, end_date, user_id).group(group_by).order('sum_actual_value ASC').sum(:actual_value)
    #return get_statistics_between(start_date, end_date).where('actual_value < 0 and internal_transaction = false').group(:name).order('sum_actual_value ASC').sum(:actual_value)
    ##.where('actual_value < 0 and internal_transaction =false').group(group_by).order('sum_actual_value ASC').sum(:actual_value)
  end

  require 'csv'
  #uses import method of referenced class CSV
  def self.import(file)
    CSV.foreach(file.path, headers: true, encoding:'iso-8859-1:utf-8') do |row|
      MontlyStatistic.create! row.to_hash
    end
  end
  
  #private
  
    def self.collect_monthly_expenses_clean(start_date, end_date, user_id)
      transactions = get_statistics_between(start_date, end_date, user_id)
      return transactions.where('actual_value < 0 and (internal_transaction = false or savings_id <> 4) and reserve = false').or(transactions.where('actual_value < 0 and reserve = true and (reserve_release = false and reserve_payment = false)'))
    end
end

app/controllers/monthly_statistics_controller.rb
class MonthlyStatisticsController < ApplicationController
  before_action :set_monthly_statistic, only: [:show, :edit, :update, :destroy]

  def get_pie_data
    @data = Array.new  
    if params[:start_date].present? && params[:end_date].present?
      @chart = MonthlyStatistic.where('period BETWEEN ? AND ?', params[:start_date], params[:end_date]).joins(:item)
      @expenses_pie = @chart.where('actual_value < 0').group(:name).sum(:actual_value)                    
      @expenses_pie.find_all do |item|
        actual_value = item[1].to_f*-1
        row = [item[0], actual_value]
        @data.push(row)
      end
      render json: @data and return false
    end
  end

  
  # GET /monthly_statistics
  # GET /monthly_statistics.json
  def index
    respond_to do |format|
    format.html
    format.json { render json: MonthlyStatisticsDatatable.new(view_context, current_user) }
    end
  end

  # GET /monthly_statistics/1
  # GET /monthly_statistics/1.json
  def show
    @monthly_statistic = MonthlyStatistic.find(params[:id])
  end

  # GET /monthly_statistics/new
  def new
    @monthly_statistic = MonthlyStatistic.new
  end

  # GET /monthly_statistics/1/edit
  def edit
    @monthly_statistic = MonthlyStatistic.find(params[:id])
  end

  # POST /monthly_statistics
  # POST /monthly_statistics.json
  def create
    @monthly_statistic = MonthlyStatistic.new(monthly_statistic_params)

    respond_to do |format|
      if @monthly_statistic.save
        format.html { redirect_to @monthly_statistic, notice: 'Monthly statistic was successfully created.' }
        format.json { render :show, status: :created, location: @monthly_statistic }
      else
        format.html { render :new }
        format.json { render json: @monthly_statistic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /monthly_statistics/1
  # PATCH/PUT /monthly_statistics/1.json
  def update
    respond_to do |format|
      if @monthly_statistic.update(monthly_statistic_params)
        format.html { redirect_to @monthly_statistic, notice: 'Monthly statistic was successfully updated.' }
        format.json { render :show, status: :ok, location: @monthly_statistic }
      else
        format.html { render :edit }
        format.json { render json: @monthly_statistic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /monthly_statistics/1
  # DELETE /monthly_statistics/1.json
  def destroy
    @monthly_statistic.destroy
    respond_to do |format|
      format.html { redirect_to monthly_statistics_url, notice: 'Monthly statistic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def import
    MonthlyStatistic.import(params[:file])
    redirect_to monthly_statistics_path, notice: "Statistics data imported"
  end
  
  def delete_all
    MonthlyStatistic.delete_all
    redirect_to monthly_statistics_path, notice: "All items deleted"    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_monthly_statistic
      @monthly_statistic = MonthlyStatistic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def monthly_statistic_params
      params.require(:monthly_statistic).permit(:period, :planned_value, :actual_value, :item_id, :hibiscus_sync_id, :match_confidence, :match_type, :match_value, :account_id, :internal_transaction, :reserve_payment, :reserve_release, :text)
    end

end

app/helpers/monthly_statistics_helper.rb
module MonthlyStatisticsHelper
end

app/views/monthly_statistics/Copy (2) of index.html.erb
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
	<!-- Content Header (Page header) -->
	<section class="content-header">
		<h1> Monthly planning <small>Income vs. expenses</small></h1>
	  	<%= render 'navigations/navigation_bar' %>
	  	<p id="notice"><%= notice %></p>
	</section>
	<% date = MonthlyStatistic.all.order(period: :asc) %>
	<% minDate = date.first.period %>
	<% maxDate = date.last.period %>
	<!-- Main content -->
	<section class="content">
	  <div class="row">
        <div class="col-md-12">
          <div class="box box-default">
            <div class="box-header with-border">
              <h3 class="box-title">Browser Usage</h3>
              <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                </button>
                <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
              </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <div class="row">
                <div class="col-md-12">
                  <div class="chart-responsive">
					<%= render 'monthly_statistics/bar_chart_expenses' %>
                  </div>
                  <!-- ./chart-responsive -->
                </div>
                <!-- /.col -->
              </div>
              <!-- /.row -->
              <div class="row">
                <div class="col-md-12">
                  <div class="chart-responsive">
					<%= render 'monthly_statistics/pie_chart_expenses'	%>
                  </div>
                  <!-- ./chart-responsive -->
                </div>
                <!-- /.col -->
              </div>
              <!-- /.row -->
            </div>
            <!-- /.box-body -->
  			<div class="box-footer">
              <div class="row">
                <div class="col-sm-4 col-xs-6">
                  <div class="description-block border-right">
                    <span class="description-percentage text-green"><i class="fa fa-caret-up"></i> 17%</span>
                    <h5 class="description-header">$35,210.43</h5>
                    <span class="description-text">TOTAL REVENUE</span>
                  </div>
                  <!-- /.description-block -->
                </div>
                <!-- /.col -->
                <div class="col-sm-4 col-xs-6">
                  <div class="description-block border-right">
                    <span class="description-percentage text-yellow"><i class="fa fa-caret-left"></i> 0%</span>
                    <h5 class="description-header">$10,390.90</h5>
                    <span class="description-text">TOTAL COST</span>
                  </div>
                  <!-- /.description-block -->
                </div>
                <!-- /.col -->
                <div class="col-sm-4 col-xs-6">
                  <div class="description-block border-right">
                    <span class="description-percentage text-green"><i class="fa fa-caret-up"></i> 20%</span>
                    <h5 class="description-header">$24,813.53</h5>
                    <span class="description-text">TOTAL PROFIT</span>
                  </div>
                  <!-- /.description-block -->
                </div>
                <!-- /.col -->
              </div>
              <!-- /.row -->
            </div>
            <!-- /.box-footer -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
		<div class="row">
			<div class="col-xs-12">
				<div class="box">
					<div class="box-header">
						<h3 class="box-title">Data Table With Full Features</h3>
					</div>

					<!-- /.box-header -->
					<div class="box-body">
						<div class="col-xs-6">		
				  			<div class="input-group date">
				      			<div class="input-group-addon">
				        			<i class="fa fa-calendar"></i>
				      			</div>
				      			<%= text_field_tag :start_date, minDate, :class => "form-control pull-right" %>
				  			</div>
			  			</div>
			  			<div class="col-xs-6">		
				  			<div class="input-group date">
				      			<div class="input-group-addon">
				        			<i class="fa fa-calendar"></i>
				      			</div>
				      			<input type="text" class="form-control pull-right" id="end_date" name="end_date" value=<%= maxDate %> >
				  			</div>
			  			</div>
					</div>
					<!-- /.box-body -->
				</div>
				<!-- /.box -->
			</div>
			<!-- /.col -->
		</div>
		<!-- /.row -->
		
		<div class="row">
			<div class="col-xs-12">
				<div class="box">
					<div class="box-header">
						<h3 class="box-title">Data Table With Full Features</h3>
					</div>
					<!-- /.box-header -->
					<div class="box-body">
						<table style="width: 67%; margin: 0 auto 2em auto;" cellspacing="0" cellpadding="3" border="0">
							<thead>
								<tr>
									<th>Filter</th>
								</tr>
							</thead>
							<tbody>
					            <tr id="filter_col7" data-column="8">
					                <td>Match type</td>
					                <td align="center"><%= select_tag "col8_filter", options_for_select([['external_account', "external_account"],['key_word', "key_word"],['item_name', "item_name"],['default', "default"]]), include_blank: "All", class:"column_filter" %> </td>
					            </tr>
					            <tr id="filter_col3" data-column="2">
					                <td>Account</td>
					                <td align="center"><%= select_tag "col2_filter", options_from_collection_for_select(Account.all, "id", "description"), include_blank: "All",  class:"column_filter" %> </td>
					            </tr>
					            <!-- {"0" => "id", "1" => "period", "2" => "account_id", "3" => "item_id", "4" => "planned_value", "5" => "actual_value", "6" => "hibiscus_sync_id", "7" => "match_confidence", "8" => "match_type", "9" => "match_value", "10" => "text"} -->
					            <tr id="filter_col4" data-column="3">
					                <td>Item</td>
					                <td align="center"><%= select_tag "col3_filter", options_from_collection_for_select(Item.all, "id", "name"), include_blank: "All",  class:"column_filter" %> </td>
					            </tr>
							</tbody>
						</table>
						<% datatable = monthly_statistics_url(format: "json") %>
						
						<table id="example1" class="display" data-source="<%= datatable %>">
							<thead>
								<tr>
									<th>#</th>
									<th>Period</th>
									<th>Account</th>
									<th>Item</th>
									<th>Planned value</th>
									<th>Actual value</th>
									<th>Hibiscus id</th>
									<th>Match confidence</th>
									<th>Match type</th>
									<th>Match value</th>
									<th>Text</th>									
								</tr>
							</thead>
							<tbody>
								<!-- automatically filled by items controller -->
							</tbody>
						</table>
					</div>
					<!-- /.box-body -->
				</div>
				<!-- /.box -->
			</div>
			<!-- /.col -->
		</div>
		<!-- /.row -->
		<div>
			<h4>Import Statistics</h4>
			<%= form_tag import_monthly_statistics_path, multipart: true do %>
			<%= file_field_tag :file %>
			<%= submit_tag "Import CSV" %>
			<% end %>
			<%= link_to 'New Monthly Statistic', new_monthly_statistic_path %>
		</div>
		<div class="form-group">
          <label for="monthlyStatisticsDeleteAll">Delete all</label>
          	<%= form_tag delete_all_monthly_statistics_path, multipart: true do %>
			<button type="submit" class="btn btn-primary">Delete all</button>
			<% end %>
        </div>
	</section>
	<!-- /.content -->
</div>
<!-- /.content-wrapper -->
<script type="text/javascript">
	var tableId = '#example1'
	myFunction(tableId)
	
	var startDate = '<%= minDate.strftime("%Y-%m-%d").to_s %>';
	var endDate = '<%= maxDate.strftime("%Y-%m-%d").to_s %>';
	
	$('#start_date').datepicker({
		autoclose: true,
		language: 'de',
		format: 'yyyy-mm-dd',
    	startDate: '<%= minDate %>',
    	endDate: '<%= maxDate %>'
	});
	
	$('#end_date').datepicker({
		autoclose: true,
		language: 'de',
		format: 'yyyy-mm-dd',
    	startDate: '<%= minDate %>',
    	endDate: '<%= maxDate %>'
	});
	
	$('#start_date').change(function() {
		update_charts();
	});
	
	$('#end_date').change(function() {
	});
	
	function update_charts(){
		var start_date = $('#start_date').val();
		var end_date = $('#end_date').val();
			$.ajax({
				url: "/monthly_statistics",

				dataType: "json",
				type: "GET",
				success: function(data) {
					
					/*var sEcho = data["sEcho"];
					var iTotalRecords = data["iTotalRecords"];
					var iTotalDisplayRecords = data["iTotalDisplayRecords"];
					var aaData = ["aaData"];
					aaData.sort(function(a, b){return a.item_id - b.item_id});*/
					//var chart = Chartkick.charts["chart-id"]
					
					Chartkick.eachChart(

						function(chart) {
							//chart.updateData(result)
							console.log(chart.getData());
							;}
					);
					
					var table = $(tableId).DataTable();
					var data = table
					    .rows()
					    .data();
					
					//console.loge(<%= datatable %>)
					//console.log(data);
					
					var result = [];
					data.reduce(function (res, value) {
						var id = value[3];
						var item_name ="test";
						function
						var item = function () {
							var result = null;
							$.ajax({
										url: "/get_item",
										data: {'id': id},
										dataType: "html",
										type: "GET",
										success: function(data) {
											result = data.name;
											//return hash(data);
											console.log(result);
											//data.toString();
											//item_name= data.name.toString();
											// = data.name;
										}
							});
							return result;
							}();
							
						console.log(item);
						var actual_value = parseFloat(value[5]);
						var expenses = 0;
						
					    if (!res[id]) {				    	
					    	
					        res[id] = [id, expenses];
					            //item: item_id,
					            //expenses: 0
					            
					        //};
					        result.push(res[id])
					    }
					    res[id][1] += actual_value
					    return res;
					}, {});
					console.log(result);
					//console.log(<%={"Football" => 10, "Basketball" => 5}%>)
						/*			
					var data = function(aaData) {
						var arrayLength = aaData.length;
						var current_item = "";
						var amount = 0;
						for (var i = 0; i < arrayLength; i++) {
							current_item = aaData[i][3];
							amount = aaData[i][5];
							if (expense < 0) { 
								if (aaData[i][3] = aaData[i-1][3]) {
									expenses += expense
															
								}
								else {
								}
								
							}						
							
							var row;
							var item = function(aaData, item) {
								var arrayLength = aaData.length;
								var data;
								var expenses = 0;
								
								for (var i = 0; i < arrayLength; i++) {
									
									

								}
								return data[item, expenses]
							}
						return row = []
					}
					
					
					var current_item = "";
					var data;
					var expenses = 0;
					

					
					for (var i = 0; i < arrayLength; i++) {
						
						row = []
						
						
						
						if (current_item <> aaData[i][3]) {
							
							data.push();
							if (expense < 0) { 
								expenses += expense
							
							}							
						}
						current_item = aaData[i][3];
						
					}
					data.push(row)*/
					//aaData["actual_value"]
					

				}
			})
	};
		/*function update_charts(){
		var start_date = $('#start_date').val();
		var end_date = $('#end_date').val();
			$.ajax({
				url: "/get_pie_data",
				data: {'start_date': start_date, 'end_date': end_date},
				dataType: "json",
				type: "GET",
				success: function(data) {
					Chartkick.eachChart(
						function(chart) {chart.updateData(data);}
					);
				}
			})
	};*/

</script>

app/views/monthly_statistics/Copy of index.html.erb
<p id="notice"><%= notice %></p>

<h1>Monthly Statistics</h1>

<table>
  <thead>
    <tr>
      <th>Period</th>
      <th>Planned value</th>
      <th>Actual value</th>
      <th>Item</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @monthly_statistics.each do |monthly_statistic| %>
      <tr>
        <td><%= monthly_statistic.period %></td>
        <td><%= monthly_statistic.planned_value %></td>
        <td><%= monthly_statistic.actual_value %></td>
        <td><%= monthly_statistic.item %></td>
        <td><%= link_to 'Show', monthly_statistic %></td>
        <td><%= link_to 'Edit', edit_monthly_statistic_path(monthly_statistic) %></td>
        <td><%= link_to 'Destroy', monthly_statistic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Monthly Statistic', new_monthly_statistic_path %>

app/views/monthly_statistics/_bar_chart_expenses.html.erb
                <div class="chart-responsive">                  	
                  <p class="text-center">
                    <strong><%= @header %></strong>
                  </p>
                    <!-- ><canvas id="pieChart" height="150"></canvas> -->
                    <!-- column_chart -->
                    <%= column_chart @data, adapter: "highcharts", library: {
								tooltip: { pointFormat: '{point.y:.2f}€' }, 
							    plotOptions: {
						        series: {
						            borderWidth: 0,
						            dataLabels: {
						                enabled: true,
						                format: '{point.y:.2f} €'
						            }
						        }
						    }
						} %>
               	</div>
                <!-- ./chart-responsive -->

app/views/monthly_statistics/_pie_chart_expenses.html.erb
                  <div class="chart-responsive">
                  <p class="text-center">
                    <strong><%= @header %></strong>
                  </p>
					<%                  data = Array.new                                
                                        @data.find_all do |item|
                                        	actual_value = item[1].to_f*-1
                                       		row = [item[0], actual_value]
									    	data.push(row)
                                        end
                    %>

                   <%=  pie_chart data, adapter: "highcharts", library: { 
                    	#chart: { height: '70%'},
                    	tooltip: { pointFormat: '<b>-{point.y:.2f}€</b>' },
                    	plotOptions: { pie: { 	allowPointSelect: true,
												cursor: 'pointer',
												dataLabels: {
																enabled: true,
																format: '{point.name}: {point.percentage:.1f} %'
												}}}}

                    %>
                  </div>
                  <!-- ./chart-responsive -->

app/views/monthly_statistics/edit.html.erb
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
	<!-- Content Header (Page header) -->
	<section class="content-header">
		<h1><%= @monthly_statistic.id %>
		  <small>edit data</small>
		</h1>
		<%= render 'navigations/navigation_bar' %>
		<%= render 'layouts/state_info' %>
	</section>
	<!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-xs-12">
          <div class="box">
          	<p id="notice"><%= notice %></p>
          <!--
            <div class="box-header">
              <h3 class="box-title">Data Table With Full Features</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
				<%= render 'form', monthly_statistic: @monthly_statistic %>
				<%= link_to 'Show', @monthly_statistic %> |
				<%= link_to 'Back', monthly_statistic_path %>
		    </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
	</section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->

app/views/monthly_statistics/new.html.erb
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
	<!-- Content Header (Page header) -->
	<section class="content-header">
		<h1>"New Statistic"</h1>
		<%= render 'navigations/navigation_bar' %>
		<%= render 'layouts/state_info' %>
	</section>
	<!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-xs-12">
          <div class="box">
          	<p id="notice"><%= notice %></p>
          <!--
            <div class="box-header">
              <h3 class="box-title">Data Table With Full Features</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
				<%= render 'form', monthly_statistic: @monthly_statistic %>
				<%= link_to 'Back', monthly_statistic_path %>
		    </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
	</section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->

app/views/monthly_statistics/show.html.erb
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
	<!-- Content Header (Page header) -->
	<section class="content-header">
		<h1><%= @monthly_statistic.id %>
		  <small>edit data</small>
		</h1>
		<%= render 'navigations/navigation_bar' %>
		<%= render 'layouts/state_info' %>
	</section>
	<!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-xs-12">
          <div class="box">
          	<p id="notice"><%= notice %></p>
          <!--
            <div class="box-header">
              <h3 class="box-title">Data Table With Full Features</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
				<%= render 'form' %>
				<%= link_to 'Edit', edit_monthly_statistic_path(@monthly_statistic) %> |
				<%= link_to 'Back', monthly_statistic_path %>
		    </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
	</section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->