config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :savings
  get 'dashboard/dashboard'
  
  resources :navigations
  resources :finance_states
  resources :accounts
  resources :monthly_statistics
  resources :items
  resources :intervals
  resources :categories
  resources :savings
  
  root to: 'dashboard#dashboard'
  
  get '/calculate_amount', to: 'items#calculate_amount'
  get '/get_pie_data', to: 'monthly_statistics#get_pie_data'
  get '/get_salaries', to: 'monthly_statistics#get_salaries'
  get '/get_date_of_last_income', to: 'monthly_statistics#get_date_of_last_income'
  get '/get_date_of_first_income', to: 'monthly_statistics#get_date_of_first_income'
   
  #get '/delete_all', to: 'monthly_statistics#delete_all'
  get '/get_item', to: 'items#get_item'
  get '/get_expenses_grouped', to: 'dashboard#get_expenses_grouped'
  
  resources :items do
    collection { post :import }  
  end
  
  resources :categories do
    collection { post :import }
  end
  
  resources :intervals do
    collection { post :import }
  end
  
  resources :navigations do
    collection { post :import }
  end
  
  resources :accounts do
    collection { post :import }
  end
  
  resources :finance_states do
    collection { post :import }
    collection { post :synchronize }
    collection { post :delete_all }
  end
  
  resources :monthly_statistics do
    collection { post :import }
    collection { post :delete_all }
  end
    
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :category
  belongs_to :interval
  belongs_to :account, optional: true
  belongs_to :saving, optional: true
  #belongs_to :id, :class_name => 'Item'
  has_many :item_id, :class_name => 'Item', :foreign_key => 'id'
  belongs_to :user
  
  validates :user, presence: true
  resourcify
  
  def calculate_planned_value
    if id.present?
      @item = Item.find(id)
      @interval = Interval.find(interval_id)
      @multiplier = Rational(@interval.numerator * @interval.denominator)
      
      calculate_planned_value = @multiplier * total_amount      
    end

    #@item.update(amount_calculated: calculate_planned_value)
    #amount_calculated = calculate_planned_value
  end
 
  
  require 'csv'
  #uses import method of referenced class CSV
  def self.import(file)
    CSV.foreach(file.path, headers: true, encoding:'iso-8859-1:utf-8') do |row|
      Item.create! row.to_hash
    end
  end
    
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  respond_to :html, :json
  add_flash_types :success, :warning, :danger, :info
  before_action :authenticate_user!
  load_and_authorize_resource

  def get_item
    if params[:id].present?
      @item = Item.find(params[:id])
      @data = Hash.new
      @data["name"] = @item.name
      render json: Item.find(params[:id]).to_json
    end
  end
  
  def calculate_amount
    if params[:interval].present? && params[:item].present? && params[:amount].present?
      @item = Item.find(params[:item])
      @interval = Interval.find(params[:interval])
      @multiplier = Rational(@interval.numerator, @interval.denominator)
      @data = Hash.new
      @calculated = @multiplier * params[:amount].to_f
      Item.where(:parent_id => @item.id).each do |child| 
        @calculated += child.amount_calculated
      end
      @data["amount_calculated"] = @calculated.round(2)
      render json: @data and return false
     end  
  end
  
  
  # GET /items
  # GET /items.json
  def index
    respond_to do |format|
    format.html
    format.json { render json: ItemsDatatable.new(view_context, current_user) }
    end
  end
  
    # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])
  end

  # GET /items/new
  def new
    @item = Item.new(:user_id => current_user.id)
  end

  # GET /items/1/edit
  def edit
    @item = Item.find(params[:id])
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)
    @item.user_id = current_user.id

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def import
    Item.import(params[:file])
    redirect_to items_path, notice: "Item data imported"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:order_id, :name, :total_amount, :amount_calculated, :reserve, :maturity, :active, :category_id, :interval_id, :key_words, :account_id, :external_account, :budget, :savings_id, :parent_id, :user_id)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_with(model: @item, local: true) do |form| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <!-- general form elements -->
  <div class="box box-primary">
    <div class="box-header with-border">
      <h3 class="box-title">Edit data</h3>
    </div>
    <!-- /.box-header -->
    <!-- form start -->
    <form role="form">
      <div class="box-body">
	  <div class="form-group">
		 <div class="field">
	    	<%= form.label :name %>
	    	<%= form.text_field :name, id: :item_name, class: "form-control", placeholder: "Test" %>
		 </div>
	  </div>
	  
	 <div class="form-group">
	    <%= form.label :category_id %>
	    <%= form.collection_select :category_id, Category.all ,:id, :name, {}, {class: "form-control select2"} %>
	  </div>
	
	  <div class="form-group">
		<div class="field">
	    	<%= form.label :total_amount %>
	    	<%= form.text_field :total_amount, id: :item_total_amount, class: "form-control", placeholder: "Test"%>
	  	</div>
	  </div>
	  <div class="form-group">
		<div class="field">
	    <%= form.label :interval_id %>
	    <%= #form.collection_select :interval_id, Interval.all ,:id, :name, {}, {class: "form-control select2", :onchange=>"calculate_amount()", :id => "item_interval_id" }
	    %>
	  	<%= form.collection_select :interval_id, Interval.all ,:id, :name, {}, {class: "form-control select2", :id => "item_interval_id" }%>
	  	</div>
	  </div>
	  <% if @item.id.present? %>
	            <div class="box box-default">
            <div class="box-header with-border">
              <h3 class="box-title">Subitems</h3>
              <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                </button>
                <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
              </div>
            </div>
            
            <!-- /.box-header -->
            <div class="box-body">
              <div class="table-responsive">
                <table class="table no-margin">
                  <thead>
                  <tr>
                    <th>Name</th>
                    <th>Planned amount</th>
                    <th>Sum</th>
                  </tr>
                  </thead>
                  <tbody>
                  	<% @rollup = 0
                  	
                  		
                  	Item.where(:parent_id => @item.id).each do |child| 
                  	@rollup += child.amount_calculated %>
                  <tr>
                    <td><%= link_to(child.name, child)  %></td>
                    <td><%= child.amount_calculated %></td>
                    <td><%= @rollup %></td>
                  </tr>
					<% 	end %>
                  </tbody>
                </table>
              </div>
              <!-- /.table-responsive -->
            </div>
            <!-- /.box-body -->
            <div class="box-footer no-padding">
            </div>
            <!-- /.footer -->
          </div>
          <!-- /.box -->
          <% end %>
	  <div class="form-group">
		<div class="field">
	    	<%= form.label :amount_calculated %>
	    	<%= form.text_field :amount_calculated, id: :item_amount_calculated, class: "form-control", placeholder: "Test", readonly: true %>
	  	</div>
	  </div>
	  <div class="form-group">
		<div class="field">
	    	<%= form.label :external_account %>
	    	<%= form.text_field :external_account, id: :item_external_account, class: "form-control", placeholder: "Test"%>
	  	</div>
	  </div>
	  		<div class="form-group">
		  <div class="field">
		    <%= form.label :key_words %>
		    <%= form.text_field :key_words, id: :item_key_words , class: "form-control", placeholder: "Test" %>
		  </div>
	  	</div>
		<div class="form-group">
		  <div class="field">
		    <%= form.label :account_id %>
		    <%= form.collection_select :account_id, Account.all ,:id, :description, {:include_blank => true}, {class: "form-control select2", :id => "item_account_id" }%>
		  </div>
	  	</div>
	  <div class="form-group">
	  	<%= form.label :maturity %>
	  	<div class="input-group date">
	      <div class="input-group-addon">
	        <i class="fa fa-calendar"></i>
	      </div>
	      <%= form.text_field :maturity, id: :item_maturity, class: "form-control pull-right" %>
	    </div>
	    <!-- /.input group -->
	  </div>
		<div class="form-group">
	    	<%= content_tag(:div, :class => "checkbox") do %>
				<%= content_tag(:label) do %>
		    		<%= form.check_box(:budget, id: :item_budget, class: "checkbox") + :budget %>
		    	<% end %>
			<% end %>
		</div>
		<div class="form-group">
	    	<%= content_tag(:div, :class => "checkbox") do %>
				<%= content_tag(:label) do %>
		    		<%= form.check_box(:reserve, id: :item_reserve, class: "checkbox") + :reserve %>
		    	<% end %>
			<% end %>
		</div>	
		<div class="form-group">
		  <div class="field">
		    <%= form.label :savings_id %>
			<%= form.collection_select :savings_id, Saving.all ,:id, :name, {}, {class: "form-control select2"} %>
			</div>
		</div>	
	    <div class="form-group">
	    	<%= content_tag(:div, :class => "checkbox") do %>
				<%= content_tag(:label) do %>
					<%= form.check_box(:active, id: :item_active, class: "checkbox") + :active %>
				<% end %>
			<% end %>
		</div>
		<div class="form-group">
		  <div class="field">
		    <%= form.label :order_id %>
		    <%= form.number_field :order_id, id: :item_order_id , class: "form-control", placeholder: "Test" %>
		  </div>
	  	</div>
		<div class="form-group">
		  <div class="field">
		    <%= form.label :parent_id %>
		    <%= form.collection_select :parent_id, Item.where('id <>?',@item.id) ,:id, :name, {:include_blank => true}, {class: "form-control select2", :id => "item_parent_id" }%>
		  </div>
	  	</div>
    </div>
  	<!-- /.box-body -->
    <div class="box-footer">
    	<button type="submit" class="btn btn-primary">Submit</button>
  	</div>
	</form>
  </div>
  <!-- /.box -->
<% end %>

<script type="text/javascript">
	$('#item_maturity').datepicker({
 			autoclose: true,
	      	format: 'dd-mm-yyyy',
	      	language: 'de'
	});

	$('#item_interval_id').change(function() {
		update_amount_calculated($(this).val());
	});
	
	$('#item_total_amount').change(function() {
		update_amount_calculated($(this).val());
	});
	
	function update_amount_calculated(input){
		var interval_id = $('#item_interval_id').val();
		var item_id = <%= @item.id %>;
		var total_amount = $('#item_total_amount').val();
		if (input != undefined) {
			$.ajax({
				url: "/calculate_amount",
				data: {'item': item_id, 'interval': interval_id, 'amount': total_amount},
				dataType: "json",
				type: "GET",
				success: function(data) {
					$('#item_amount_calculated').val(data["amount_calculated"]).text(data["amount_calculated"]);
				}
			})
		}
	};
</script>

app/views/items/edit.html.erb
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
	<!-- Content Header (Page header) -->
	<section class="content-header">
		<h1><%= @item.name %>
		  <small>edit data</small>
		</h1>
		<%= render 'navigations/navigation_bar' %>
		<%= render 'layouts/state_info' %>
	</section>
	<!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-xs-12">
          <div class="box">
          	<p id="notice"><%= notice %></p>
          <!--
            <div class="box-header">
              <h3 class="box-title">Data Table With Full Features</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
				<%= render 'form' %>
				<%= link_to 'Edit', edit_item_path(@item) %> |
				<%= link_to 'Back', items_path %>
		    </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
	</section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->

app/views/items/index.html.erb
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
	<!-- Content Header (Page header) -->
	<section class="content-header">
		<h1> Monthly planning <small>Income vs. expenses</small></h1>
		<!-- <ol class="breadcrumb"> -->
		<%= render 'navigations/navigation_bar' %>
	</section>

	<!-- Main content -->
	<section class="content">
		<div class="row">
			<div class="col-xs-12">
				<div class="box">
					<div class="box-header">
						<h3 class="box-title">Data Table With Full Features</h3>
					</div>
					<!-- /.box-header -->
					<div class="box-body">
						<table style="width: 67%; margin: 0 auto 2em auto;" cellspacing="0" cellpadding="3" border="0">
							<thead>
								<tr>
									<th>Filter</th>
								</tr>
							</thead>
							<tbody>
					            <tr id="filter_col8" data-column="7">
					                <td>Column - Name</td>
					                <td align="center"><%= select_tag "col7_filter", options_from_collection_for_select(Category.all, "id", "name"), include_blank: "All", class:"column_filter" %> </td>
					            </tr>
					            <tr id="filter_col7" data-column="6">
					                <td>Column - Salary</td>
					                <td align="center"><%= select_tag "col6_filter", options_for_select([['Active', "1"],['Inactive', "0"]]), include_blank: "All", class:"column_filter" %> </td>
					            </tr> 
							</tbody>
						</table>
						<table id="example1" class="display" data-source="<%= items_url(format: "json") %>">
							<thead>
								<tr>
									<th>Order</th>
									<th>Name</th>
									<th>Total amount</th>
									<th>Amount calculated</th>
									<th>Reserve</th>
									<th>Maturity</th>
									<th>Active</th>
									<th>Category</th>
									<th>Interval</th>
									<th>Rollup</th>
									<th>Account</th>
									<th>External account</th>
									<th>Key words</th>
									<th colspan="3"></th>
								</tr>
							</thead>
							<tbody>
								<!-- automatically filled by items controller -->
							</tbody>
						</table>
					</div>
					<!-- /.box-body -->
				</div>
				<!-- /.box -->
			</div>
			<!-- /.col -->
		</div>
		<!-- /.row -->
		<div>
	    <div class="form-group">
          <label for="itemsInputFile">Import as CSV</label>
          	<%= form_tag import_items_path, multipart: true do %>
			<%= file_field_tag :file %>
			<button type="submit" class="btn btn-primary">Submit</button>
			<% end %>
			<%= link_to 'New Item', new_item_path %>
        </div>

	</section>
	<!-- /.content -->
</div>
<!-- /.content-wrapper -->
<script type="text/javascript">
	var tableId = '#example1'
	myFunction(tableId)
</script>

app/views/items/new.html.erb
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
	<!-- Content Header (Page header) -->
	<section class="content-header">
		<h1>New item</h1>
		<%= render 'navigations/navigation_bar' %>
		<%= render 'layouts/state_info' %>
	</section>
	<!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-xs-12">
          <div class="box">
          	<p id="notice"><%= notice %></p>
          <!--
            <div class="box-header">
              <h3 class="box-title">Data Table With Full Features</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
				<%= render 'form', item: @item %>
				<%= link_to 'Back', items_path %>
		    </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
	</section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->

app/views/items/show.html.erb
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
	<!-- Content Header (Page header) -->
	<section class="content-header">
		<h1><%= @item.name %>
		  <small>edit data</small>
		</h1>
		<%= render 'navigations/navigation_bar' %>
		<%= render 'layouts/state_info' %>
	</section>
	<!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-xs-12">
          <div class="box">
          	<p id="notice"><%= notice %></p>
          <!--
            <div class="box-header">
              <h3 class="box-title">Data Table With Full Features</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
				<%= render 'form' %>
				<%= link_to 'Edit', edit_item_path(@item) %> |
				<%= link_to 'Back', items_path %>
		    </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
	</section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->