config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :savings
  get 'dashboard/dashboard'
  
  resources :navigations
  resources :finance_states
  resources :accounts
  resources :monthly_statistics
  resources :items
  resources :intervals
  resources :categories
  resources :savings
  
  root to: 'dashboard#dashboard'
  
  get '/calculate_amount', to: 'items#calculate_amount'
  get '/get_pie_data', to: 'monthly_statistics#get_pie_data'
  get '/get_salaries', to: 'monthly_statistics#get_salaries'
  get '/get_date_of_last_income', to: 'monthly_statistics#get_date_of_last_income'
  get '/get_date_of_first_income', to: 'monthly_statistics#get_date_of_first_income'
   
  #get '/delete_all', to: 'monthly_statistics#delete_all'
  get '/get_item', to: 'items#get_item'
  get '/get_expenses_grouped', to: 'dashboard#get_expenses_grouped'
  
  resources :items do
    collection { post :import }  
  end
  
  resources :categories do
    collection { post :import }
  end
  
  resources :intervals do
    collection { post :import }
  end
  
  resources :navigations do
    collection { post :import }
  end
  
  resources :accounts do
    collection { post :import }
  end
  
  resources :finance_states do
    collection { post :import }
    collection { post :synchronize }
    collection { post :delete_all }
  end
  
  resources :monthly_statistics do
    collection { post :import }
    collection { post :delete_all }
  end
    
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  has_many :items
  belongs_to :user
  has_many :transactions, :class_name => 'Transaction'
  has_many :monthly_statistics, :through => :transactions
  
  validates :user, presence: true
  resourcify

  require 'csv'
  #uses import method of referenced class CSV
  def self.import(file)
    CSV.foreach(file.path, headers: true, encoding:'iso-8859-1:utf-8') do |row|
      Account.create! row.to_hash
    end
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]
  respond_to :html, :json
  before_action :authenticate_user!
  load_and_authorize_resource

  # GET /accounts
  # GET /accounts.json
  def index   
    respond_to do |format|
    format.html
    format.json { render json: AccountsDatatable.new(view_context, current_user) }
    end
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
    @account = Account.find(params[:id])
  end

  # GET /accounts/new
  def new
    @account = Account.new(:user_id => current_user.id)
  end

  # GET /accounts/1/edit
  def edit
    @account = Account.find(params[:id])
  end

  # POST /accounts
  # POST /accounts.json
  def create
    
    @account = Account.new(account_params)
    @account.user_id = current_user.id
    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def import
    Account.import(params[:file])
    redirect_to accounts_path, notice: "Account data imported"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:account_number, :description, :iban, :bic, :hibiscus_account_id, :item_id, :user_id)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<%= form_with(model: @account, local: true) do |form| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!-- general form elements -->
  <div class="box box-primary">
    <div class="box-header with-border">
      <h3 class="box-title">Edit data</h3>
    </div>
    <!-- /.box-header -->
    <!-- form start -->
    <form role="form">
      <div class="box-body">
	  <div class="form-group">
		 <div class="field">
	    	<%= form.label :account_number %>
	    	<%= form.text_field :account_number, id: :account_account_number, class: "form-control", placeholder: "Test" %>
		 </div>
	  </div>
	  <div class="form-group">
		 <div class="field">
	    	<%= form.label :description %>
	    	<%= form.text_field :description, id: :account_description, class: "form-control", placeholder: "Test" %>
		 </div>
	  </div>	  
	  <div class="form-group">
		 <div class="field">
	    	<%= form.label :iban %>
	    	<%= form.text_field :iban, id: :account_iban, class: "form-control", placeholder: "Test" %>
		 </div>
	  </div>	  
	  <div class="form-group">
		 <div class="field">
	    	<%= form.label :bic %>
	    	<%= form.text_field :bic, id: :account_bic, class: "form-control", placeholder: "Test" %>
		 </div>
	  </div>
	  <div class="form-group">
		 <div class="field">
	    	<%= form.label :hibiscus_account_id %>
	    	<%= form.text_field :hibiscus_account_id, id: :account_account_id, class: "form-control", placeholder: "Test" %>
		 </div>
	  </div>
	  <div class="form-group">
		 <div class="field">
	    	<%= form.label :item_id %>
	  	<%= form.collection_select :item_id, Item.all ,:id, :name,  {:include_blank => true}, {class: "form-control select2", :id => "item_id" }%>
		 </div>
	  </div>	
    </div>
  	<!-- /.box-body -->
    <div class="box-footer">
    	<button type="submit" class="btn btn-primary">Submit</button>
  	</div>
	</form>
  </div>
  <!-- /.box -->
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
	<!-- Content Header (Page header) -->
	<section class="content-header">
		<h1> Monthly planning <small>Income vs. expenses</small></h1>
	  	<%= render 'navigations/navigation_bar' %>
	  	<p id="notice"><%= notice %></p>
	</section>
	<!-- Main content -->
	<section class="content">
		<div class="row">
			<div class="col-xs-12">
				<div class="box">
					<div class="box-header">
						<h3 class="box-title">Data Table With Full Features</h3>
					</div>
					<!-- /.box-header -->
					<div class="box-body">
						<table style="width: 67%; margin: 0 auto 2em auto;" cellspacing="0" cellpadding="3" border="0">
							<thead>
								<tr>
									<th>Filter</th>
								</tr>
							</thead>
							<tbody>

							</tbody>
						</table>
						<table id="example1" class="display" data-source="<%= accounts_url(format: "json") %>">
							<thead>
								<tr>
									<th>#</th>
									<th>Account #</th>
									<th>Description</th>
									<th>IBAN</th>
									<th>BIC</th>
									<th>Hibiscus account id</th>
									<th>Item id</th>
									<th>Edit</th>
									<th>Delete</th>
								</tr>
							</thead>
							<tbody>
								<!-- automatically filled by items controller -->
							</tbody>
						</table>
					</div>
					<!-- /.box-body -->
				</div>
				<!-- /.box -->
			</div>
			<!-- /.col -->
		</div>
		<!-- /.row -->
		<div>
			<h4>Import Statistics</h4>
			<%= form_tag import_accounts_path, multipart: true do %>
			<%= file_field_tag :file %>
			<%= submit_tag "Import CSV" %>
			<% end %>
			<%= link_to 'New Account', new_account_path %>
		</div>
	</section>
	<!-- /.content -->
</div>
<!-- /.content-wrapper -->
<script type="text/javascript">
	var tableId = '#example1'
	myFunction(tableId)
</script>

app/views/accounts/new.html.erb
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
	<!-- Content Header (Page header) -->
	<section class="content-header">
		<h1>New account</h1>
		<%= render 'navigations/navigation_bar' %>
		<p id="notice"><%= notice %></p>
	</section>
	<!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-xs-12">
          <div class="box">
          	<p id="notice"><%= notice %></p>
          <!--
            <div class="box-header">
              <h3 class="box-title">Data Table With Full Features</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
				<%= render 'form' %>
				<%= link_to 'Back', accounts_path %>
		    </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
	</section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->

app/views/accounts/show.html.erb
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
	<!-- Content Header (Page header) -->
	<section class="content-header">
		<h1><%= @account.iban %>
		  <small>edit data</small>
		</h1>
		<%= render 'navigations/navigation_bar' %>
		<p id="notice"><%= notice %></p>
	</section>
	<!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-xs-12">
          <div class="box">
          	<p id="notice"><%= notice %></p>
          <!--
            <div class="box-header">
              <h3 class="box-title">Data Table With Full Features</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
				<%= render 'form' %>
				<%= link_to 'Edit', edit_account_path(@account) %> |
				<%= link_to 'Back', accounts_path %>
		    </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
	</section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->